theme: minima
title: The trendy blog
author: Luca Iacolino
email: luca.iacolino@mail.com
description: > # this means to ignore newlines until "baseurl:"
  A Trendy blog made by Luca Iacolino

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
